AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/AbcSize:
  Max: 31

Metrics/BlockLength:
  Max: 57

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 33

Style/AsciiComments:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false
